controllers:
    resource:
        path: ../src/Domain
        namespace: App\Domain
    type: attribute

nelmio_api_doc:
    resource: '@NelmioApiDocBundle/config/routing/swaggerui.xml'
    prefix: /api/doc