parameters:
    REDIS_DSN: '%env(REDIS_DSN)%'
    GOOGLE_CLIENT_ID: '%env(GOOGLE_CLIENT_ID)%'
    GOOGLE_CLIENT_SECRET: '%env(GOOGLE_CLIENT_SECRET)%'
    GITHUB_CLIENT_ID: '%env(GITHUB_CLIENT_ID)%'
    GITHUB_CLIENT_SECRET: '%env(GITHUB_CLIENT_SECRET)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'

    App\Shared\Service\RedisService:
        arguments:
            $redisDsn: '%env(REDIS_DSN)%'

    App\Domain\Auth\Controller\AuthController:
        tags: ['controller.service_arguments']

    Google\Client:
        calls:
            - [setClientId, ['%env(GOOGLE_CLIENT_ID)%']]
            - [setClientSecret, ['%env(GOOGLE_CLIENT_SECRET)%']]

    App\Domain\Auth\Service\AuthService:
        arguments:
            $googleClientId: '%env(GOOGLE_CLIENT_ID)%'
            $githubClientId: '%env(GITHUB_CLIENT_ID)%'
            $githubClientSecret: '%env(GITHUB_CLIENT_SECRET)%'

    App\Shared\Security\JwtAuthenticator:
        arguments:
            $authService: '@App\Domain\Auth\Service\AuthService'