lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/%env(JWT_SECRET_KEY)%'
    public_key: '%kernel.project_dir%/%env(JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600
    user_id_claim: sub
    token_extractors:
        authorization_header:
            enabled: true
            prefix: Bearer
            name: Authorization

