# config/packages/security.yaml
security:
  password_hashers:
    App\Entity\User:
      algorithm: auto
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    api:
      pattern: ^/auth 
      stateless: true
      jwt: ~ 
  access_control:
    - { path: ^/auth/(login|register|refresh)$, roles: PUBLIC_ACCESS } 
    - { path: ^/auth/logout$, roles: IS_AUTHENTICATED_FULLY } 

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10